//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLGearModifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLGearModifier.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty_Albedo.png.
        /// </summary>
        internal static string EmptyAlbedoFilename {
            get {
                return ResourceManager.GetString("EmptyAlbedoFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty_Maskpbr_Map.png.
        /// </summary>
        internal static string EmptyMaskFilename {
            get {
                return ResourceManager.GetString("EmptyMaskFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty_Normal_Map.png.
        /// </summary>
        internal static string EmptyNormalFilename {
            get {
                return ResourceManager.GetString("EmptyNormalFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D_4128E5C7.
        /// </summary>
        internal static string EyesAlbedoPropertyName {
            get {
                return ResourceManager.GetString("EyesAlbedoPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D_BEC07F52.
        /// </summary>
        internal static string EyesNormalPropertyName {
            get {
                return ResourceManager.GetString("EyesNormalPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D_B56F9766.
        /// </summary>
        internal static string EyesRgmtaoPropertyName {
            get {
                return ResourceManager.GetString("EyesRgmtaoPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _texture_color.
        /// </summary>
        internal static string HairAlbedoPropertyName {
            get {
                return ResourceManager.GetString("HairAlbedoPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _texture_normal.
        /// </summary>
        internal static string HairNormalPropertyName {
            get {
                return ResourceManager.GetString("HairNormalPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _texture_maskpbr.
        /// </summary>
        internal static string HairRgmtaoPropertyName {
            get {
                return ResourceManager.GetString("HairRgmtaoPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _BaseColorMap.
        /// </summary>
        internal static string HDRPLitAlbedoPropertyName {
            get {
                return ResourceManager.GetString("HDRPLitAlbedoPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NormalMap.
        /// </summary>
        internal static string HDRPLitNormalPropertyName {
            get {
                return ResourceManager.GetString("HDRPLitNormalPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MaskMap.
        /// </summary>
        internal static string HDRPLitRgmtaoPropertyName {
            get {
                return ResourceManager.GetString("HDRPLitRgmtaoPropertyName", resourceCulture);
            }
        }
    }
}
